### ISSUE TITLE
Faulty chat links

### ISSUE THREAD

**Issue by SoupleCodes** [mybearworld/roarer#107]
**Link doesn't take you to page when clicking chat links you've joined:**

![Screenshot 2024-05-07 5 49 41 PM](https://github.com/mybearworld/roarer/assets/161522024/103e6e66-5f76-4d10-ad1a-3a793a2c351d)
Link above is the url of the soup group chat

![Screenshot 2024-05-07 5 49 26 PM](https://github.com/mybearworld/roarer/assets/161522024/48a3182b-12d4-4cc7-bed3-8638a7a1f81c)
Link above is the url i clicked, which in this case is "https://mybearworld.github.io/roarer/#/chats/25ecd679-e81b-4cc0-a388-0652a8e2abc2", "🦖 Dinonuggie's EMPIRE 🦖", but it doesn't take you there. Reloading the tab will get you to the group chat link you've clicked.

**Comment by mybearworld** [comment]
Can't replicate this - what browser/OS are you on?

**Comment by SoupleCodes** [comment]
> Can't replicate this - what browser/OS are you on?

ChromeOS Google Chrome
Just go to a group chat and click a different group chat link.

**Comment by SoupleCodes** [comment]
You can go to my group chat here:
https://mybearworld.github.io/roarer/#/chats/61e6f424-a738-4cbb-9525-d61d686b6eac
If you look below, i did a command with my @SoupBot that allowed it to posts all empire group chat links. Click one of the links.

**Comment by mybearworld** [comment]
This only happens in group chats, I can replicate it now

**Comment by SoupleCodes** [comment]
> This only happens in group chats, I can replicate it now

Good to hear

**Comment by mybearworld** [comment]
This seems to have the same root cause as #102, I'll use that to have everything in one place
