### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mybearworld** [mybearworld/roarer#17]
Potentially.
Not sure if anyone would translate lol

**Comment by NotFenixio** [comment]
I would be willing to translate Roarer to Spanish.

**Comment by OneShot-Niko** [comment]
> I would be willing to translate Roarer to Spanish.

same goes for hungarian

**Comment by mybearworld** [comment]
Done in https://github.com/mybearworld/roarer/commit/e093172ef8032aec7b05d9b6cce89c40bb0a2659!

**Comment by OneShot-Niko** [comment]
> Done in [e093172](https://github.com/mybearworld/roarer/commit/e093172ef8032aec7b05d9b6cce89c40bb0a2659)!

gonna try PR'ing for a hungarian translation possibly soon then
