### ISSUE TITLE
Notifications for DMs

### ISSUE THREAD

**Issue by mybearworld** [mybearworld/roarer#20]
> **dango**
> and we do not get notifications from dm'ing so no much point

> **mybearworld**
> hmm possible roarer feature?

> **dango**
> real

**Comment by mybearworld** [comment]
Unfortunately, it doesn't look like it's possible to store information on an account :(

**Comment by OneShot-Niko** [comment]
> Unfortunately, it doesn't look like it's possible to store information on an account :(

RIP

**Comment by OneShot-Niko** [comment]
About this, considering GCs now have a mini-popup, mayve that could be done for dms as well?
Unless rhat exists and I just remember wrong

**Comment by mybearworld** [comment]
> About this, considering GCs now have a mini-popup, mayve that could be done for dms as well? Unless that exists and I just remember wrong

DMs do that too - it's just that if you happen to miss the toast, you won't know.
