### ISSUE TITLE
Roarer is amazing, Just one little thing.

### ISSUE THREAD

**Issue by oofy123** [mybearworld/roarer#28]
I would like an option to zoom in or make the ui a little bigger.
Thats basically it. - helloitsme

**Comment by NotFenixio** [comment]
You can use Ctrl + or Ctrl - to zoom in and zoom out. Note that this is a feature from your browser and not really from Roarer.

**Comment by OneShot-Niko** [comment]
> You can use Ctrl + or Ctrl - to zoom in and zoom out. Note that this is a feature from your browser and not really from Roarer.

Note: If you have multiple tabs open, you will also have to hold Shift unless you are using the Numpad's + and -.

**Comment by mybearworld** [comment]
> You can use Ctrl + or Ctrl - to zoom in and zoom out. Note that this is a feature from your browser and not really from Roarer.

Yeah, I think that's the best solution.
