### ISSUE TITLE
List the other unlisted PFPs (-1, 500 & 102)

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#29]
[F Client](https://new-meower-f-client.vercel.app/) already does this and it's allowed (atleast from what I can tell since I've used Spinny Meowy for around 5 days now)

By the other pfps that are unlisted, I mean these:
![kép](https://github.com/mybearworld/roarer/assets/150537842/ba479f4d-9eb9-4c9c-a778-52135e83c7c6)
Those should all work on Meower if I remember right.
IDs of these ones are:
-1 (Spinny)
500
102 (Server)
~~404 (Don't know and haven't even seen on the normal client unfortunately)~~ Does not appear to sync & appear on normal client
~~-3~~ Does not appear to sync & appear on normal client

**Comment by mybearworld** [comment]
None of these are in the [avatars folder](https://github.com/meower-media-co/Meower-Svelte/tree/master/src/assets/avatars). Do they really all work on Meower Svelte?

**Comment by OneShot-Niko** [comment]
> None of these are in the [avatars folder](https://github.com/meower-media-co/Meower-Svelte/tree/master/src/assets/avatars). Do they really all work on Meower Svelte?

Besides questionmark & -3 they appear most of them sync on Meower Svelte

**Comment by OneShot-Niko** [comment]
> None of these are in the [avatars folder](https://github.com/meower-media-co/Meower-Svelte/tree/master/src/assets/avatars?rgh-link-date=2024-01-05T16%3A09%3A32Z). Do they really all work on Meower Svelte?

Did a look again found most: 
[icon_guest.svg / Guest / Dotted Meowy](https://github.com/meower-media-co/Meower-Svelte/blob/master/src/assets/avatars/icon_guest.svg)
[icon_err.svg / Error / -3, note that this is also -1 aka spinny meowy however needs a spin affect added](https://github.com/meower-media-co/Meower-Svelte/blob/master/src/assets/avatars/icon_err.svg)
I am going to look for the server one

**Comment by OneShot-Niko** [comment]
> > None of these are in the [avatars folder](https://github.com/meower-media-co/Meower-Svelte/tree/master/src/assets/avatars?rgh-link-date=2024-01-05T17%3A48%3A59Z). Do they really all work on Meower Svelte?
> 
> Did a look again found most: [icon_guest.svg / Guest / Dotted Meowy](https://github.com/meower-media-co/Meower-Svelte/blob/master/src/assets/avatars/icon_guest.svg?rgh-link-date=2024-01-05T17%3A48%3A59Z) [icon_err.svg / Error / -3, note that this is also -1 aka spinny meowy however needs a spin affect added](https://github.com/meower-media-co/Meower-Svelte/blob/master/src/assets/avatars/icon_err.svg?rgh-link-date=2024-01-05T17%3A48%3A59Z) I am going to look for the server one

Whoops server exists as well:
[icon_101.svg / Server](https://github.com/meower-media-co/Meower-Svelte/blob/develop/src/assets/avatars/icon_101.svg)
