### ISSUE TITLE
Add your contribution here!

### ISSUE THREAD

**Issue by mybearworld** [mybearworld/roarer#38]
Have you contributed in any way, and are not on the list in the README?

If so, please create a comment like so:

> @allcontributors please add @Someone for ideas, bug, code

The bot will create a PR, and I'll merge it. Thank you for contributing to Roarer!

**Comment by OneShot-Niko** [comment]
Wait, why is this getting closed & pinned at the same time though? Shouldn't this be left open?

**Comment by mybearworld** [comment]
@allcontributors add @NotFenixio for ideas, bug

**Comment by mybearworld** [comment]
@allcontributors add @Supernoodles99 for design

**Comment by mybearworld** [comment]
@allcontributors add @Supernoodles99 for design

(just in case :P)

**Comment by mybearworld** [comment]
@allcontributors add @Supernoodles99 for ideas, bug

**Comment by PaperMarioFan-2022** [comment]
Hey, maybe I can help? I'm experienced in IT, but not advanced coding, but I started with github before.

**Comment by showierdata9978** [comment]
@allcontributors add @ShowierData9978 ideas, sends discord emojis

**Comment by mybearworld** [comment]
@allcontributors add @3r1s-s for ideas (~~stealing from~~ <ins>getting inspired by</ins> meo)
