### ISSUE TITLE
profile images stretch

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#45]
Unsure if this is a bug, so I'll just submit this issue as I also don't have too much time as of making this.

For example:

![kép](https://github.com/mybearworld/roarer/assets/150537842/f4266ea0-0a7a-4bac-ab7a-6760c0bddf49)

This goes with permissions mostly.

**Comment by mybearworld** [comment]
This is intentional - should it work differently?

**Comment by OneShot-Niko** [comment]
> This is intentional - should it work differently?

Apologies then - Thought it wasn't for some reason.
