### ISSUE TITLE
usernames suddenly get a linebreak added if too long due to post date

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#46]
EDIT: Hovering over a post by a really long username pushes the username into peices.
Now that I think of it, this may be intentional, but even then it looks really weird from a UX-perspective

https://github.com/mybearworld/roarer/assets/150537842/c8a19b71-9ed9-4490-b9fe-aa527e974f3a

**Comment by mybearworld** [comment]
I thought I fixed that :P Thanks, will look into why my fix isn't working

**Comment by mybearworld** [comment]
I can't seem to replicate this, even with that exact username:
![image](https://github.com/mybearworld/roarer/assets/130385691/7d66513e-076b-4795-ad2f-22955f49504d)

**Comment by OneShot-Niko** [comment]
I know you mentioned this in meower but I get error'd out so gotta say here
Pretty sure the username youre using is shorter
I think it should happen at the limit, forgot

**Comment by OneShot-Niko** [comment]
resolved
pog
