### ISSUE TITLE
scratchblocks support

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#50]
![kép](https://github.com/mybearworld/roarer/assets/150537842/bfaf2302-dcb8-4ad6-88e6-c565a3cac24a)
its fair this doesnt get implemented or gets closed as wontfix as pretty sure that was just sarcasm but
making issue anyway
EDIT: First problem is definitely the fact that this can end up being just huge for vanilla client users (and/or people using clients that dont support it the same way)

**Comment by NotFenixio** [comment]
Scratchblocks have an option for changing the scale of the blocks anyways. 

Maybe check if the language from the codeblock tag (` ``` `) is scratch and put the contents of it in a \<pre> tag so it gets rendered?

**Comment by NotFenixio** [comment]
In fact: https://github.com/scratchblocks/scratchblocks?tab=readme-ov-file#html

**Comment by mybearworld** [comment]
The problem with that is that you'd have to rerun the renderMatching call on every single new post or edit, which is probably wasteful.

**Comment by NotFenixio** [comment]
Maybe render the blocks in each post instead of in the entire page? It's not that wasteful this way.

**Comment by mybearworld** [comment]
> Maybe render the blocks in each post instead of in the entire page? It's not that wasteful this way.

Yeah, I think that would be the best option. This would work a lot better if `parseMarkdown` was a component instead of a function..

**Comment by mybearworld** [comment]
> > Maybe render the blocks in each post instead of in the entire page? It's not that wasteful this way.
> 
> Yeah, I think that would be the best option. This would work a lot better if `parseMarkdown` was a component instead of a function..

Did that now in https://github.com/mybearworld/roarer/commit/adf32d30d2ba7c2ccd7f9fa7d96f6cc3413904f6!

**Comment by OneShot-Niko** [comment]
> Did that now in [adf32d3](https://github.com/mybearworld/roarer/commit/adf32d30d2ba7c2ccd7f9fa7d96f6cc3413904f6)!

thank you!!!
