### ISSUE TITLE
Add reporting to profiles.

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#53]
On Meower, you can report on profiles directly:
![profile](https://github.com/mybearworld/roarer/assets/150537842/739eda74-98a5-4813-a71a-b3008a3c0f4d)
The modal itself is straightforward:
![reportmodal](https://github.com/mybearworld/roarer/assets/150537842/e3ae0819-2242-4787-816d-bfcda4ffc2fa)

This'd be nice so inappropriate usernames can be reported through there.
Though ig fair this doesnt exist in roarer (atleast yet?) since you can just report through posts anyways but
if its unrelated to any of their posts it just won't make much sense

**Comment by mybearworld** [comment]
Done in https://github.com/mybearworld/roarer/commit/b4872baceae4c87ceb195470da3a0673c05ddf52

**Comment by OneShot-Niko** [comment]
> Done in [b4872ba](https://github.com/mybearworld/roarer/commit/b4872baceae4c87ceb195470da3a0673c05ddf52)

tysm
