### ISSUE TITLE
Any image attachment (discord/markdown) is rendered as "Download (...)" instead of previewed.

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#66]
Roarer:
![kép](https://github.com/mybearworld/roarer/assets/150537842/b3dbf6a7-b013-4dc2-984d-f5aefbc484b0)
https://mybearworld.github.io/roarer/#/posts/098a7b7b-3aea-4767-a960-cecc9810e510
Meower:
![kép](https://github.com/mybearworld/roarer/assets/150537842/068d61e0-a651-4f99-adb3-f312ac635b47)

**Comment by OneShot-Niko** [comment]
Turns out this also happens with markdown.

**Comment by mybearworld** [comment]
Fixed that :P

**Comment by OneShot-Niko** [comment]
> Fixed that :P

thank you mybearworld!
