### ISSUE TITLE
yet another emoji in the discord

### ISSUE THREAD

**Issue by Supernoodles99** [mybearworld/roarer#67]
`<:atticusaijkndemw:1212216821625917450>`

**Comment by mybearworld** [comment]
This sounds very trustworthy
![response from Eris to my question: "is atticusaijkndemw on the server?" with "Perhaps"](https://github.com/mybearworld/roarer/assets/130385691/fc8e0452-a1d1-451e-a81c-093f2fa183a1)

**Comment by showierdata9978** [comment]
its in the server
