### ISSUE TITLE
Online indicators go to the wrong position when the post is too large

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#80]
found on:
![kép](https://github.com/mybearworld/roarer/assets/150537842/42992c2c-ccea-4173-b253-28e14c79e2d0)
https://mybearworld.github.io/roarer#/posts/e86350a5-5b43-4abd-bd0e-afc9eeae6c14
test post:
![kép](https://github.com/mybearworld/roarer/assets/150537842/a3199ce1-db54-4d75-abd1-43c5b73a2576)
https://mybearworld.github.io/roarer#/posts/a62b0281-c3d4-4a1d-8e2f-392145e1a5e6

on post urls, it goes to the bottom right:
![kép](https://github.com/mybearworld/roarer/assets/150537842/c250f7ce-a09f-4ce6-b888-d6638e51adae)

EDIT: It looks like this moves _all the online indicators_ to the same position.

**Comment by SoupleCodes** [comment]
goofy AHHH GREEN DOT DDDDD:
