### ISSUE TITLE
PostIDs get censored

### ISSUE THREAD

**Issue by OneShot-Niko** [mybearworld/roarer#87]
https://mybearworld.github.io/roarer#/posts/6569ae48-cef0-4202-8b33-f6e462ebb64f

Slight issue is that this might not be fixable - Unless if the first line of the post includes a ping + then msg, then it gets uncensored - The issue is that it'd need joining, and that way it'd probably not be possible to have replies in the middle of the post, even though that [currently doesnt exist](https://mybearworld.github.io/roarer#/posts/7dbf25a5-fbb4-49e9-a8b5-bd5fa624e411) this might be a bit of an issue if that's ever taken to be implemented

**Comment by mybearworld** [comment]
Welp, that's an edge case I've always wondered about but could never come up with any circumstance where that would happen. Thanks, will look into how that could be fixed

**Comment by OneShot-Niko** [comment]
> Welp, that's an edge case I've always wondered about but could never come up with any circumstance where that would happen. 

I didn't think about this either honestly lol

> Thanks, will look into how that could be fixed

np and good luck

**Comment by mybearworld** [comment]
I have an idea on how to approach this, let's see

**Comment by OneShot-Niko** [comment]
> ~I have an idea on how to approach this, let's see~ Wait, no, that doesn't work - you can manually put `****` into your posts. Back to the drawing board :P

okay this may not be the best idea in terms of performance, but how about postIDs are attempted to be scraped from the message and then whitelisted in localstorage? That shouldn't add up too much since swears in the IDs are rare, so it shouldnt have much harm

**Comment by ajskateboarder** [comment]
To fix this, you could pass the post ID through Meower's filter before posting, and if inappropriate, create another post ID

**Comment by tnix100** [comment]
thanks uuid4
![image](https://github.com/mybearworld/roarer/assets/61485190/c723361b-0a8a-4158-b130-acfe9f594d85)

This is such a rare scenario I don't think you need to worry about implementing a fix for. We are removing the profanity filter in the next server update as the new age requirements policy will go into effect soon.

**Comment by OneShot-Niko** [comment]
> We are removing the profanity filter in the next server update as the new age requirements policy will go into effect soon.

Right - Forgot about that.

**Comment by mybearworld** [comment]
> We are removing the profanity filter in the next server update as the new age requirements policy will go into effect soon.

Awesome
