### ISSUE TITLE
Better group chat support

### ISSUE THREAD

**Issue by mybearworld** [mybearworld/roarer#9]
- [X] Creating group chats (https://github.com/mybearworld/roarer/commit/d1631e921b0f0acda7bcbae83255e6a8ebee11b5)
- [X] Creating DMs (https://github.com/mybearworld/roarer/commit/e14f42761b1870f99426c91f8db1f5074d3050ee)
- [X] Administrating group chats (https://github.com/mybearworld/roarer/commit/ac4d534c2d71b74b6a1e2c7809a623cec06a82de)

**Comment by zzthebooplister** [comment]
i believe you'll need the api for this, forgor what link tho :P

**Comment by mybearworld** [comment]
> i believe you'll need the api for this, forgor what link tho :P

I'm very glad the server is open source, I can find what I want very easily like that

**Comment by mybearworld** [comment]
Making these issues is surprisingly useful lol
It's done now!
