### ISSUE TITLE
Pasting images into the message input and uploading them to Imgbb

### ISSUE THREAD

**Issue by NotFenixio** [mybearworld/roarer#96]
I've started this at https://github.com/NotFenixio/roarer/tree/imgbb but I can't figure out how to update the imgbbApiKey localstorage item when the input changes. 
I also created a lib for uploading images, but didn't really test it :P

I think it would be cool to have a feature like this so users don't have to manually upload an image everytime they, for example, make a screenshot.

Of course they'd need to add their Imgbb API key for this to work.

**Comment by mybearworld** [comment]
I don't have an ImgBB account to test this with, so that might be a bit difficult.

>  but I can't figure out how to update the imgbbApiKey localstorage item when the input changes.

`v-model="settingsStore.imgbbApiKey"` should do it?
