### ISSUE TITLE
New Theme: Material You Orange

### ISSUE THREAD

**Issue by Rubiidev-18** [mybearworld/roarer#97]
Theme Data: ```{"v":1,"orange":"#432304","background":"#261303","foreground":"#e1d4cb","foregroundOrange":"#e6c6a8","roarer_link":"#d1853d","roarer_postStyle":"filled","roarer_colorScheme":"dark","orangeLight":"#432304","orangeDark":"#432304","tinting":"#432304"}```
Hope this gets added to this client! (maybe with a better name like Lion)

**Comment by mybearworld** [comment]
What's your Meower account? I'd like to give credit for the theme.

**Comment by Rubiidev-18** [comment]
> What's your Meower account? I'd like to give credit for the theme.

sorry for late reply, it's Scratchgaming2222

**Comment by mybearworld** [comment]
Thanks! Sorry it took me so long to get to this.
